#!/usr/bin/env python3
"""
月次PDCA分析スクリプト (GitHub Models版・完全無料)

GitHub Actions の cron で毎月1日に実行。
data/{YYYY-MM}/ に人間がcommitした売上CSVを GitHub Models(無料)で分析し、
reports/{YYYY-MM}-pdca.md にレポートを生成する。

【フロー】
  人間が月初5分でCSVを手動取得・commit → このスクリプトが自動分析 → レポートcommit
"""

import datetime
import os
import sys
from pathlib import Path

from openai import OpenAI

ROOT = Path(__file__).resolve().parents[3]
DATA_DIR = ROOT / "projects" / "rakuda-sensei" / "data"
REPORTS_DIR = ROOT / "projects" / "rakuda-sensei" / "reports"
KPI_PATH = ROOT / "knowledge" / "pdca-kpi.md"

GH_MODELS_ENDPOINT = "https://models.github.ai/inference"
MODEL = "openai/gpt-4o-mini"
MAX_TOKENS = 4096


def collect_data(target_month: str) -> dict[str, str]:
    """data/{YYYY-MM}/ 配下のCSV・テキストファイルを収集"""
    month_dir = DATA_DIR / target_month
    files = {}

    if not month_dir.exists():
        return files

    for f in month_dir.iterdir():
        if f.suffix in (".csv", ".txt", ".md"):
            try:
                files[f.name] = f.read_text(encoding="utf-8")
            except Exception:
                files[f.name] = f"(読み込みエラー: {f.name})"

    return files


def build_pdca_prompt(month: str, data: dict[str, str], kpi_md: str) -> str:
    data_section = ""
    if data:
        for filename, content in data.items():
            data_section += f"\n### {filename}\n```\n{content[:3000]}\n```\n"
    else:
        data_section = "\n（データファイルなし）\n"

    prev_month = (
        datetime.datetime.strptime(month, "%Y-%m") - datetime.timedelta(days=1)
    ).strftime("%Y-%m")

    return f"""あなたは「残業嫌いのらくだ先生🐪」のビジネスアナリストです。
{month}の副業（note/BOOTH/Kindle）の月次PDCAレポートを作成してください。

==== KPI・目標 ====
{kpi_md[:2000]}

==== {month}の売上データ ====
{data_section}

==== レポート要件 ====
- 言語: 日本語
- 各チャネル（note/BOOTH/Kindle/X）の数値評価
- 目標対比（達成率）
- 良かった点、改善点
- 翌月({prev_month}の次＝来月)のアクション3〜5個（具体的・実行可能なもの）
- 撤退ライン確認（pdca-kpi.mdの撤退条件に該当するか）

==== 出力フォーマット ====
# {month} 月次PDCAレポート

## サマリー
- 総売上: ¥XXX
- note: ¥XX（目標比 XX%）
- BOOTH: ¥XX（目標比 XX%）
- Kindle: ¥XX（目標比 XX%）
- X フォロワー: XXX人（前月比 ±XX）

## Check（振り返り）
### 良かった点
- ...

### 改善が必要な点
- ...

## Action（翌月のアクション）
1. ...（優先度高）
2. ...
3. ...

## 撤退ライン確認
| チャネル | 撤退条件 | 現状 | 判定 |
|------|------|------|------|
| note | ... | ... | 継続/要注意/撤退 |
| BOOTH | ... | ... | 継続/要注意/撤退 |
| Kindle | ... | ... | 継続/要注意/撤退 |

## 備考
- AI生成レポート（要人間確認）
- データなし項目は推定値または「データ待ち」と明記
"""


def main() -> int:
    token = os.environ.get("GITHUB_TOKEN")
    if not token:
        print("ERROR: GITHUB_TOKEN が設定されていません", file=sys.stderr)
        return 1

    # 対象月の決定（前月 = 分析対象）
    if len(sys.argv) > 1:
        target_month = sys.argv[1]  # 手動指定: YYYY-MM
    else:
        today = datetime.date.today()
        first_of_this_month = today.replace(day=1)
        prev_month = first_of_this_month - datetime.timedelta(days=1)
        target_month = prev_month.strftime("%Y-%m")

    print(f"📊 分析対象月: {target_month}")

    data = collect_data(target_month)
    if not data:
        print(f"WARNING: {DATA_DIR / target_month}/ にデータファイルがありません")
        print("  → 管理画面から売上CSVを取得してcommitしてから再実行してください")
        print("  → (空のレポートを生成して継続します)")

    kpi_md = KPI_PATH.read_text(encoding="utf-8") if KPI_PATH.exists() else ""

    print(f"🤖 モデル: {MODEL} (GitHub Models・無料)")
    print(f"📁 データファイル数: {len(data)}件")

    client = OpenAI(base_url=GH_MODELS_ENDPOINT, api_key=token)
    response = client.chat.completions.create(
        model=MODEL,
        max_tokens=MAX_TOKENS,
        temperature=0.4,  # 分析は低めの温度で安定させる
        messages=[
            {
                "role": "user",
                "content": build_pdca_prompt(target_month, data, kpi_md),
            }
        ],
    )

    body = response.choices[0].message.content or ""
    usage = response.usage

    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    out_path = REPORTS_DIR / f"{target_month}-pdca.md"

    header = (
        f"<!-- AUTO-GENERATED by monthly_pdca.py ({datetime.datetime.now().isoformat(timespec='seconds')}) -->\n"
        f"<!-- Model: {MODEL} (GitHub Models・無料) -->\n"
        f"<!-- Tokens: in={usage.prompt_tokens if usage else '?'} out={usage.completion_tokens if usage else '?'} -->\n"
        f"<!-- ⚠️ AI生成レポートです。数値は必ず管理画面で確認してください。 -->\n\n"
    )

    out_path.write_text(header + body, encoding="utf-8")
    print(f"✅ PDCAレポート生成完了: {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
